name: flutter_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^2.0.1
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  http: ^1.2.0
  image_picker: ^1.0.7
  stomp_dart_client: ^3.0.1
  provider: ^6.1.1
  fl_chart: ^0.66.0
  intl: ^0.19.0
  google_generative_ai: ^0.4.6  # Thư viện Gemini chính chủ
  flutter_markdown: ^0.7.3
  speech_to_text: ^7.2.0  # Thư viện chuyển giọng nói thành chữ


  # Google
  google_sign_in: 6.2.1
  mobile_scanner: 5.2.3

  # Bluetooth
  flutter_blue_plus: ^1.34.5

  # Permission
  permission_handler: ^11.3.1

dependency_overrides:
  google_sign_in_ios: 5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



# Phần quan trọng nhất ở đây
flutter:
  uses-material-design: true

  # Khai báo assets (Thụt vào 2 dấu cách so với chữ flutter)
  assets:
    # Chỉ cần dòng này là nó tự nhận hết ảnh trong thư mục
    - assets/images/
    - assets/icons/