name: flutter_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2  # <-- Thêm dòng này nha vợ
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^2.0.1
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0  # Để lấy vị trí
  http: ^1.2.0
  google_sign_in: ^6.1.6  # Để lấy Token từ Google
  mobile_scanner: ^5.1.0 # Hoặc bản mới nhất
  flutter_blue_plus: ^1.34.5
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Phần quan trọng nhất ở đây
flutter:
  uses-material-design: true

  # Khai báo assets (Thụt vào 2 dấu cách so với chữ flutter)
  assets:
    # Chỉ cần dòng này là nó tự nhận hết ảnh trong thư mục
    - assets/images/
    - assets/icons/